name: Daily Express Entry Email Alert

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run email alert script
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        SMTP_HOST: ${{ secrets.SMTP_HOST }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: python email_alert.py
    - name: Commit updated last_sent.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add last_sent.json
        git commit -m "Update last_sent.json after email sent" || echo "No changes to commit"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
