name: Daily Draw Scraper

on:
  schedule:
    # 8:00 AM EST = 13:00 UTC
    - cron: '0 13 * * 1-5'
    # 6:00 PM EST = 23:00 UTC
    - cron: '0 23 * * 1-5'
  workflow_dispatch:      # Allows manual trigger

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python scrape_express_entry_draws.py

      - name: Commit and Push if Changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add express_entry_draws.csv
          git commit -m "🔄 Update draw data [CI]" || echo "No changes to commit"
          git push
